### ISSUE TITLE
Indicator Lists

### ISSUE THREAD

**Issue by tjmisko** [tjmisko/sspi-data-webapp#276]
1. List of Indicator Codes known to require reworking or with bad data coverage
2. List of Indicator Codes with Dynamic Data collected in a CSV or other local file format.
3. List of Indicator Codes with API sources still to be written

*Reply with Lists in Comment to Close*

**Comment by maxstrr** [comment]
List of Indicator Codes known to require reworking or with bad data coverage:
[“GTRANS”, “ATLNRG”, “COALPW”, “BEEFMK”, “WATMAN”, “MSWGEN”, “EWASTE”, “RECYCL”, “TAXEVA”, “ISHRAT”, “PHYSPC”, “TRNETW”, “CYBSEC”, “PUBACC”]

Indicators with Dynamic Data collected in a CSV or other local file format (done):
[“NITROG”, “DEFRST”, “CARBON”, “CRPTAX”, “CSTUNT”, “AQELEC”, “RULELW”, “PUBSRV”, “EDEMOC”]

Indicators with Dynamic Data collected in a CSV or other format (not done):
[“ARMEXP, “MILEXP”, “SECAPP”, “GENDEQ”, “UNCONV”, “CSTUNT”]

List of Indicator Codes with API sources still to be written:
[“CHILDW”, “COLBAR”, “LFPART”, “UNEMPL”, “MATERN”, “FATINJ”, “FSTABL”]

List of Indicators which (to my knowledge) only need to be computed:
[“TAXREV”, “GINIPT”, “ENRPRI”, “ENRSEC”, “PUPTCH”, “FAMPLN”, “MURDER”, “PRISON”, “RDFUND”, “FORAID”]

List of Indicators which are we are “done” with:
[“BIODIV, “REDLST”, “STKHLM”, “NRGINT”, “AIRPOL”, “SENIOR”, “FDEPTH”, “ATBRTH”, “DPTCOV”, “DRKWAT”, “SANSRV”, “INTRNT”]
